# Generated by Django 4.2.7 on 2023-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_confirm_password_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USERNAME_FIELD',
            field=models.CharField(default='Username', max_length=50, verbose_name='Primeiro Nome'),
        ),
    ]
