# Generated by Django 4.2.7 on 2023-12-17 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_user_username_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Último nome')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], default=None, max_length=1, verbose_name='sexo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(default='11111111111', max_length=11, verbose_name='cpf')),
                ('address', models.CharField(max_length=255, verbose_name='Rua/Avenida')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=None, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='cep')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('password', models.CharField(max_length=20, verbose_name='Senha')),
                ('confirm_password', models.CharField(default=None, max_length=20, verbose_name='Confirmar Senha')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
